spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kata
    username: postgres
    password: new_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  config: classpath:logback.xml